import "./globals.css"
import type { Metadata } from "next"
import FooterNewsletter from "@/components/ui/footer-newsletter"

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body>
        {children}
        <FooterNewsletter />
      </body>
    </html>
  )
}
